"""ban_system

Revision ID: 19a59d851bb2
Revises: 649cacd2200b
Create Date: 2026-07-12 10:44:47.605875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19a59d851bb2'
down_revision: Union[str, Sequence[str], None] = '649cacd2200b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banned_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ban_code', sa.Enum('JL', 'JS', 'AS', 'MB', 'HD', name='bancode'), nullable=False),
    sa.Column('banned_at', sa.DateTime(), nullable=False),
    sa.Column('ban_duration', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('telegram_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'users', ['telegram_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'telegram_id')
    op.drop_table('banned_users')
    # ### end Alembic commands ###
